[package]
name = "get_input"
version = "0.1.0"
edition = "2021"
#authors = ["Bha-Gu "]
license = "MIT"
description = "A library to get input from CLI"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
